// Generated by scripts/harsi-art.js from src/art/people/svg. Do not edit by hand:
// change the SVG files and run `node scripts/harsi-art.js build`.

/** Hand-drawn people art, as SVG markup keyed by name. */
export const PEOPLE_SVG: Record<string, string> = {

};
