// Generated by scripts/harsi-art.js from src/art/harsi/svg. Do not edit by hand:
// change the SVG files and run `node scripts/harsi-art.js build`.

/** Hand-drawn Ħarsi art, as SVG markup keyed by name. */
export const HARSI_SVG: Record<string, string> = {

};
